import { createFileRoute, Link, useParams, useSearch } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { getDriverProfileAI } from "@/lib/ai-search";
import { ArrowLeft, Trophy, Award, Flag, Target, History, TrendingUp } from "lucide-react";
import { getTeamColor, Team } from "@/lib/f1-data";
import { StatCard } from "@/components/StatCard";
import { LoadingScreen } from "@/components/LoadingScreen";
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";

import { z } from "zod";

export const Route = createFileRoute("/archive/$driverId")({
  validateSearch: (search: Record<string, unknown>) => {
    return {
      name: z.string().optional().parse(search.name),
    };
  },
  head: (ctx: any) => ({
    meta: [
      { title: `${ctx.search?.name || 'Driver'} Archive Profile · APEX F1` },
      { name: "description", content: "Historical F1 driver profile generated by AI." },
    ],
  }),
  component: ArchiveProfilePage,
});

function ArchiveProfilePage() {
  const { driverId } = useParams({ from: "/archive/$driverId" });
  const { name } = useSearch({ from: "/archive/$driverId" }) as { name: string };

  const { data: d, isLoading } = useQuery({
    queryKey: ["driverProfileAI", name || driverId],
    queryFn: () => getDriverProfileAI(name || driverId),
    staleTime: Infinity, // Career stats don't change
  });

  if (isLoading) return <LoadingScreen />;
  if (!d) return (
    <div className="flex min-h-[60vh] flex-col items-center justify-center gap-4 text-center">
      <h2 className="text-2xl font-display uppercase">Deep Dive Failed</h2>
      <p className="text-muted-foreground">The archive could not retrieve data for this driver.</p>
      <Link to="/drivers" className="text-primary hover:underline">Return to Repository</Link>
    </div>
  );

  const lastTeam = d.teams[d.teams.length - 1];
  const mainTeamName = typeof lastTeam === 'object' ? lastTeam.name : lastTeam;
  const mainTeam = (mainTeamName || "Ferrari") as Team;

  return (
    <div className="pb-16 animate-in fade-in duration-700">
      {/* HERO SECTION */}
      <section className="relative overflow-hidden border-b border-border">
        <div
          className="absolute inset-0 opacity-[0.15]"
          style={{
            background: `radial-gradient(ellipse at top right, ${getTeamColor(mainTeam)}, transparent 60%)`,
          }}
        />
        <div className="absolute inset-0 grid-bg opacity-30" />
        <div className="pointer-events-none absolute -right-6 top-4 font-display text-[260px] leading-none text-stroke select-none opacity-40">
          {d.championships > 0 ? "WDC" : "LEG"}
        </div>
        
        <div className="relative mx-auto max-w-7xl px-6 py-10">
          <Link
            to="/drivers"
            className="inline-flex items-center gap-1.5 text-[12px] text-muted-foreground hover:text-foreground mb-6 transition-colors"
          >
            <ArrowLeft className="h-3.5 w-3.5" /> Archive Repository
          </Link>
          
          <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.2em] text-primary mb-3">
            <History className="h-3 w-3" /> Archive Dossier · {d.nationality}
          </div>
          
          <h1 className="font-display text-7xl md:text-9xl leading-none tracking-tighter mb-4">
            {d.name.split(' ').slice(0, -1).join(' ').toUpperCase()}{" "}
            <span className="text-primary">{d.name.split(' ').slice(-1)[0].toUpperCase()}</span>
          </h1>
          
          <div className="flex flex-wrap gap-x-8 gap-y-3 text-[13px] text-muted-foreground">
            <div className="flex items-center gap-2">
              <TrendingUp className="h-4 w-4 text-primary" />
              <span>Active for <strong className="text-foreground">{d.yearsActive}</strong> Seasons</span>
            </div>
            {d.championships > 0 && (
              <div className="flex items-center gap-2">
                <Trophy className="h-4 w-4 text-warning" />
                <span><strong className="text-foreground">{d.championships}</strong> World Titles ({d.championshipYears.join(', ')})</span>
              </div>
            )}
          </div>
        </div>
      </section>

      <div className="mx-auto max-w-7xl px-6 py-10 space-y-8">
        {/* STAT CARDS */}
        <div className="grid gap-4 grid-cols-2 lg:grid-cols-4">
          <StatCard
            label="World Titles"
            value={d.championships}
            sub="Championships"
            icon={<Trophy className="h-4 w-4" />}
            accent
          />
          <StatCard
            label="Grand Prix Wins"
            value={d.totalWins}
            sub="Career Wins"
            icon={<Award className="h-4 w-4" />}
          />
          <StatCard
            label="Podium Finishes"
            value={d.totalPodiums}
            sub="Total Career"
            icon={<Target className="h-4 w-4" />}
          />
          <StatCard
            label="Race Starts"
            value={d.totalStarts}
            sub="Professional Career"
            icon={<Flag className="h-4 w-4" />}
          />
        </div>

        <div className="grid gap-6 lg:grid-cols-[2fr_1fr]">
          {/* CAREER GROWTH GRAPH */}
          <div className="rounded-xl border border-border bg-surface-1 p-6 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none">
              <TrendingUp className="h-32 w-32" />
            </div>
            <h3 className="mb-8 text-[11px] font-bold uppercase tracking-[0.2em] text-muted-foreground">
              Career Growth & Performance Index
            </h3>
            <div className="h-[300px] w-full mt-4">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={d.careerGraph} margin={{ top: 10, right: 30, left: -20, bottom: 0 }}>
                  <XAxis dataKey="year" stroke="var(--muted-foreground)" fontSize={10} tickMargin={10} />
                  <YAxis 
                    reversed 
                    domain={[1, 'dataMax']} 
                    stroke="var(--muted-foreground)" 
                    fontSize={10}
                    tickFormatter={(v) => `P${v}`}
                  />
                  <Tooltip 
                    contentStyle={{ backgroundColor: 'var(--surface-2)', border: 'none', borderRadius: '12px', fontSize: '12px', boxShadow: '0 10px 30px rgba(0,0,0,0.5)' }}
                    itemStyle={{ color: 'var(--primary)', fontWeight: 'bold' }}
                    formatter={(value: number) => [`P${value}`, 'Finishing Position']}
                  />
                  <Line 
                    type="monotone" 
                    dataKey="pos" 
                    stroke="var(--primary)" 
                    strokeWidth={4}
                    dot={{ r: 5, fill: "var(--surface-1)", strokeWidth: 2 }}
                    activeDot={{ r: 8, fill: "var(--primary)" }}
                    animationDuration={2000}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="space-y-6">
            {/* AI SUMMARY */}
            <div className="rounded-xl border border-border bg-surface-1 p-6 border-l-4 border-l-primary">
              <h3 className="mb-4 text-[11px] font-bold uppercase tracking-[0.2em] text-primary flex items-center gap-2">
                <History className="h-3 w-3" /> AI Strategic Overview
              </h3>
              <p className="text-sm text-foreground leading-relaxed italic">
                "{d.aiSummary}"
              </p>
            </div>

            {/* CAREER LEGACY */}
            <div className="rounded-xl border border-border bg-surface-1 p-6">
              <h3 className="mb-4 text-[11px] font-bold uppercase tracking-[0.2em] text-muted-foreground">
                Career Legacy
              </h3>
              <p className="text-sm text-foreground/80 leading-relaxed">
                {d.legacy}
              </p>
            </div>
          </div>
        </div>

        {/* TEAM LINEAGE */}
        <div className="rounded-xl border border-border bg-surface-1 p-6">
          <h3 className="mb-6 text-[11px] font-bold uppercase tracking-[0.2em] text-muted-foreground">
            Constructor Lineage
          </h3>
          <div className="flex flex-wrap items-center gap-x-4 gap-y-3">
            {d.teams.map((team: any, i: number) => {
              const name = typeof team === 'string' ? team : team.name;
              const years = typeof team === 'string' ? "" : team.years;
              
              return (
                <div key={i} className="flex items-center gap-4">
                  <div className="text-sm font-medium text-foreground">
                    {name} {years && <span className="ml-1 text-muted-foreground">({years})</span>}
                  </div>
                  {i < d.teams.length - 1 && (
                    <div className="text-muted-foreground/40">→</div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
