/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as DriversIndexRouteImport } from './routes/drivers.index'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as RaceRaceIdRouteImport } from './routes/race.$raceId'
import { Route as PrincipalTeamIdRouteImport } from './routes/principal.$teamId'
import { Route as DriverDriverIdRouteImport } from './routes/driver.$driverId'
import { Route as ArchiveDriverIdRouteImport } from './routes/archive.$driverId'

const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriversRoute,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceRaceIdRoute = RaceRaceIdRouteImport.update({
  id: '/race/$raceId',
  path: '/race/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalTeamIdRoute = PrincipalTeamIdRouteImport.update({
  id: '/principal/$teamId',
  path: '/principal/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDriverIdRoute = DriverDriverIdRouteImport.update({
  id: '/driver/$driverId',
  path: '/driver/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveDriverIdRoute = ArchiveDriverIdRouteImport.update({
  id: '/archive/$driverId',
  path: '/archive/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/docs': typeof DocsRoute
  '/drivers': typeof DriversRouteWithChildren
  '/live': typeof LiveRoute
  '/news': typeof NewsRoute
  '/seasons': typeof SeasonsRoute
  '/archive/$driverId': typeof ArchiveDriverIdRoute
  '/driver/$driverId': typeof DriverDriverIdRoute
  '/principal/$teamId': typeof PrincipalTeamIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/drivers/': typeof DriversIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/docs': typeof DocsRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRoute
  '/seasons': typeof SeasonsRoute
  '/archive/$driverId': typeof ArchiveDriverIdRoute
  '/driver/$driverId': typeof DriverDriverIdRoute
  '/principal/$teamId': typeof PrincipalTeamIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/drivers': typeof DriversIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/docs': typeof DocsRoute
  '/drivers': typeof DriversRouteWithChildren
  '/live': typeof LiveRoute
  '/news': typeof NewsRoute
  '/seasons': typeof SeasonsRoute
  '/archive/$driverId': typeof ArchiveDriverIdRoute
  '/driver/$driverId': typeof DriverDriverIdRoute
  '/principal/$teamId': typeof PrincipalTeamIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/drivers/': typeof DriversIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/docs'
    | '/drivers'
    | '/live'
    | '/news'
    | '/seasons'
    | '/archive/$driverId'
    | '/driver/$driverId'
    | '/principal/$teamId'
    | '/race/$raceId'
    | '/team/$teamId'
    | '/drivers/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/docs'
    | '/live'
    | '/news'
    | '/seasons'
    | '/archive/$driverId'
    | '/driver/$driverId'
    | '/principal/$teamId'
    | '/race/$raceId'
    | '/team/$teamId'
    | '/drivers'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/docs'
    | '/drivers'
    | '/live'
    | '/news'
    | '/seasons'
    | '/archive/$driverId'
    | '/driver/$driverId'
    | '/principal/$teamId'
    | '/race/$raceId'
    | '/team/$teamId'
    | '/drivers/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DocsRoute: typeof DocsRoute
  DriversRoute: typeof DriversRouteWithChildren
  LiveRoute: typeof LiveRoute
  NewsRoute: typeof NewsRoute
  SeasonsRoute: typeof SeasonsRoute
  ArchiveDriverIdRoute: typeof ArchiveDriverIdRoute
  DriverDriverIdRoute: typeof DriverDriverIdRoute
  PrincipalTeamIdRoute: typeof PrincipalTeamIdRoute
  RaceRaceIdRoute: typeof RaceRaceIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof DriversRoute
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race/$raceId': {
      id: '/race/$raceId'
      path: '/race/$raceId'
      fullPath: '/race/$raceId'
      preLoaderRoute: typeof RaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/$teamId': {
      id: '/principal/$teamId'
      path: '/principal/$teamId'
      fullPath: '/principal/$teamId'
      preLoaderRoute: typeof PrincipalTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/$driverId': {
      id: '/driver/$driverId'
      path: '/driver/$driverId'
      fullPath: '/driver/$driverId'
      preLoaderRoute: typeof DriverDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$driverId': {
      id: '/archive/$driverId'
      path: '/archive/$driverId'
      fullPath: '/archive/$driverId'
      preLoaderRoute: typeof ArchiveDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DriversRouteChildren {
  DriversIndexRoute: typeof DriversIndexRoute
}

const DriversRouteChildren: DriversRouteChildren = {
  DriversIndexRoute: DriversIndexRoute,
}

const DriversRouteWithChildren =
  DriversRoute._addFileChildren(DriversRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DocsRoute: DocsRoute,
  DriversRoute: DriversRouteWithChildren,
  LiveRoute: LiveRoute,
  NewsRoute: NewsRoute,
  SeasonsRoute: SeasonsRoute,
  ArchiveDriverIdRoute: ArchiveDriverIdRoute,
  DriverDriverIdRoute: DriverDriverIdRoute,
  PrincipalTeamIdRoute: PrincipalTeamIdRoute,
  RaceRaceIdRoute: RaceRaceIdRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
